### ISSUE TITLE
Rewrite it in Rust

### ISSUE THREAD

**Issue by chop0** [zhuowei/nft_ptr#6]
Whilst C++ is cool and all, these days Rust is really where it's at.  Eventually, it would be ideal to move the entire thing to Rust smart pointers, but as a transition, using C++/Rust bindings would be an excellent solution.

**Comment by chop0** [comment]
update: nevermind it's already rust

**Comment by zhuowei** [comment]
I used Solidity for the smart contracts in this project since it had to run on Ethereum and I wanted to use OpenZeppelin's prebuilt templates, but I'm open to rewriting the smart contracts in Rust for WebAssembly-enabled blockchains.
